# pull node image
FROM node:14.13.0-alpine

# set working directory
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json ./
RUN npm install --silent
RUN npm i react-scripts@3.4.1 -g --silent

# add app
COPY . ./

# start app

CMD ["npm","start"]
