# pull node image
FROM node:14.13.0-alpine as create

# set working directory
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json ./

RUN npm ci  --silent
RUN npm i react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

# production env
FROM nginx:stable-alpine
COPY --from=create /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]

